#lang rosette

(provide (all-defined-out))

(define BPF_ALU #x04)
(define BPF_ALU64 #x07)

(define BPF_W #x00)
(define BPF_H #x08)
(define BPF_B #x10)
(define BPF_DW #x18)

(define BPF_IMM #x00)
(define BPF_ABS #x20)
(define BPF_IND #x40)
(define BPF_MEM #x60)
(define BPF_XADD #xc0)

(define BPF_K #x00)
(define BPF_X #x08)

(define BPF_ADD #x00)
(define BPF_SUB #x10)
(define BPF_MUL #x20)
(define BPF_DIV #x30)
(define BPF_OR  #x40)
(define BPF_AND #x50)
(define BPF_LSH #x60)
(define BPF_RSH #x70)
(define BPF_NEG #x80)
(define BPF_MOD #x90)
(define BPF_XOR #xa0)
(define BPF_MOV #xb0)
(define BPF_ARSH #xc0)
(define BPF_END #xd0)

(define BPF_JA #x00)
(define BPF_JMP #x05)
(define BPF_JEQ #x10)
(define BPF_JGT #x20)
(define BPF_JGE #x30)
(define BPF_JSET #x40)
(define BPF_JNE #x50)
(define BPF_JSGT #x60)
(define BPF_JSGE #x70)
(define BPF_CALL #x80)
(define BPF_EXIT #x90)
(define BPF_JLT #xa0)
(define BPF_JLE #xb0)
(define BPF_JSLT #xc0)
(define BPF_JSLE #xd0)

(define BPF_LD #x00)
(define BPF_LDX #x01)
(define BPF_ST #x02)
(define BPF_STX #x03)

(define R0 0)
(define R1 1)
(define R2 2)
(define R3 3)
(define R4 4)
(define R5 5)
(define R6 6)
(define R7 7)
(define R8 8)
(define R9 9)
(define R10 10)
